# Generated by Django 6.0.7 on 2026-07-07 22:08

import curator.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('source_type', models.CharField(choices=[('ticketmaster_api', 'Ticketmaster Api'), ('ics', 'Ics'), ('rss', 'Rss'), ('json_ld', 'Json Ld'), ('html_config', 'Html Config'), ('playwright_config', 'Playwright Config'), ('manual', 'Manual')], max_length=30)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('enabled', models.BooleanField(default=True)),
                ('crawl_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('parser_config', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('reliability_score', models.IntegerField(default=0)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_address', models.CharField(max_length=500, unique=True)),
                ('normalized_address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('geocoded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('center_latitude', models.FloatField(blank=True, null=True)),
                ('center_longitude', models.FloatField(blank=True, null=True)),
                ('default_radius_miles', models.PositiveIntegerField(default=25)),
                ('timezone', models.CharField(default='America/Chicago', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('time_is_known', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='America/Chicago', max_length=64)),
                ('venue_name', models.CharField(blank=True, max_length=300)),
                ('address_line', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('price_text', models.CharField(blank=True, max_length=200)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('needs_review', 'Needs Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('duplicate', 'Duplicate')], default='needs_review', max_length=20)),
                ('quality_score', models.IntegerField(default=0)),
                ('duplicate_group_key', models.CharField(blank=True, db_index=True, max_length=300)),
                ('editorial_notes', models.TextField(blank=True)),
                ('approved_for_digest', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='curator.event')),
                ('primary_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_events', to='curator.eventsource')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='curator.region')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial_success', 'Partial Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('events_found_count', models.IntegerField(default=0)),
                ('events_created_count', models.IntegerField(default=0)),
                ('events_updated_count', models.IntegerField(default=0)),
                ('events_rejected_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('raw_log', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_runs', to='curator.eventsource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RawImportedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload_json', models.JSONField(blank=True, default=dict)),
                ('raw_title', models.TextField(blank=True)),
                ('raw_description', models.TextField(blank=True)),
                ('raw_start', models.CharField(blank=True, max_length=200)),
                ('raw_end', models.CharField(blank=True, max_length=200)),
                ('raw_location', models.TextField(blank=True)),
                ('raw_url', models.URLField(blank=True, max_length=1000)),
                ('extraction_status', models.CharField(choices=[('extracted', 'Extracted'), ('normalized', 'Normalized'), ('rejected', 'Rejected'), ('error', 'Error')], default='extracted', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_events', to='curator.importrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_events', to='curator.eventsource')),
            ],
        ),
        migrations.AddField(
            model_name='eventsource',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='curator.region'),
        ),
        migrations.CreateModel(
            name='DigestIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('subject_line', models.CharField(max_length=300)),
                ('intro_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('sent', 'Sent'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('target_start_date', models.DateField()),
                ('target_end_date', models.DateField()),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_issues', to='curator.region')),
            ],
            options={
                'ordering': ['-target_start_date'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained')], default='active', max_length=20)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('confirmation_token', models.CharField(default=curator.models.make_token, max_length=64, unique=True)),
                ('unsubscribe_token', models.CharField(default=curator.models.make_token, max_length=64, unique=True)),
                ('last_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='curator.region')),
            ],
        ),
        migrations.CreateModel(
            name='EmailSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_provider_message_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('digest_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_sends', to='curator.digestissue')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_sends', to='curator.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='DigestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('top_picks', 'Top picks'), ('family_friendly', 'Family-friendly'), ('free_cheap', 'Free or cheap'), ('date_night', 'Date night'), ('music_food', 'Music, food, and downtown'), ('outdoor_markets', 'Outdoor, markets, and festivals'), ('worth_the_drive', 'Worth the drive'), ('next_week', 'Coming up next week')], max_length=30)),
                ('position', models.PositiveIntegerField(default=0)),
                ('custom_blurb', models.TextField(blank=True)),
                ('include_in_email', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('digest_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_events', to='curator.digestissue')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_appearances', to='curator.event')),
            ],
            options={
                'ordering': ['section', 'position'],
                'constraints': [models.UniqueConstraint(fields=('digest_issue', 'event'), name='unique_event_per_digest')],
            },
        ),
        migrations.CreateModel(
            name='EventSourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_title', models.CharField(blank=True, max_length=500)),
                ('source_payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='curator.event')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='curator.eventsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'source', 'source_url'), name='unique_event_source_url')],
            },
        ),
        migrations.AddConstraint(
            model_name='eventsource',
            constraint=models.UniqueConstraint(fields=('region', 'slug'), name='unique_source_slug_per_region'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['region', 'status', 'starts_at'], name='curator_eve_region__996a8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(fields=('region', 'email'), name='unique_subscriber_per_region'),
        ),
    ]
