# Generated by Django 6.0.7 on 2026-07-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsource',
            name='source_type',
            field=models.CharField(choices=[('ticketmaster_api', 'Ticketmaster Api'), ('ics', 'Ics'), ('rss', 'Rss'), ('json_ld', 'Json Ld'), ('html_config', 'Html Config'), ('playwright_config', 'Playwright Config'), ('whereabouts_api', 'Whereabouts Api'), ('manual', 'Manual')], max_length=30),
        ),
    ]
