# Generated by Django 6.0.7 on 2026-07-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0002_alter_eventsource_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
