# Generated by Django 6.0.7 on 2026-07-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0003_event_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestissue',
            name='media_alt',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='digestissue',
            name='media_caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='digestissue',
            name='media_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='digestissue',
            name='media_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='digestissue',
            name='media_placement',
            field=models.CharField(choices=[('after_intro', 'After the intro'), ('before_footer', 'Before the footer')], default='after_intro', max_length=20),
        ),
        migrations.AddField(
            model_name='digestissue',
            name='media_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='digestevent',
            name='section',
            field=models.CharField(choices=[('top_picks', 'Top Picks'), ('family_friendly', 'Family Fun'), ('free_cheap', 'Free or Cheap'), ('date_night', 'Date Night'), ('music_food', 'Music & Food'), ('outdoor_markets', 'Outdoor & Markets'), ('hidden_gem', 'Hidden Gem'), ('worth_the_drive', 'Worth the Short Drive'), ('next_week', 'Looking Ahead')], max_length=30),
        ),
    ]
