# Generated by Django 6.0.7 on 2026-07-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0004_digestissue_media_alt_digestissue_media_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestevent',
            name='custom_title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
