# Generated by Django 6.0.7 on 2026-07-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0005_digestevent_custom_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestevent',
            name='custom_location',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
