# Generated by Django 6.0.7 on 2026-07-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0006_digestevent_custom_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestissue',
            name='rendered_html',
            field=models.TextField(blank=True),
        ),
    ]
