# Generated by Django 6.0.7 on 2026-07-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0008_remap_digest_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestevent',
            name='section',
            field=models.CharField(choices=[('top_picks', 'Top Picks'), ('family_fun', 'Family Fun'), ('music_nightlife', 'Music & Nightlife'), ('food_markets', 'Food, Markets & Downtown'), ('outdoors_active', 'Outdoors & Active'), ('arts_community', 'Arts & Community'), ('hidden_gem', 'Hidden Gem'), ('worth_the_drive', 'Worth the Short Drive'), ('next_week', 'Looking Ahead')], max_length=30),
        ),
    ]
