# Generated by Django 6.0.7 on 2026-07-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0009_alter_digestevent_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestevent',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
