# Generated by Django 6.0.7 on 2026-07-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0011_digestsection_digestevent_custom_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestevent',
            name='custom_price',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
