# Generated by Django 6.0.7 on 2026-07-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0012_digestevent_custom_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
